name: candlesticks
description: A high-performance full featured candlesticks chart for all platforms.
version: 2.1.2
homepage: https://github.com/r-mzy47/candlesticks

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: 3.13.6

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: